# Generated by Django 4.1.7 on 2023-03-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_homename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Content image')),
                ('name', models.CharField(max_length=60, verbose_name='Content name')),
                ('text', models.TextField(verbose_name='Content text')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Content date')),
            ],
        ),
    ]
