# Generated by Django 4.1.7 on 2023-03-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=60, verbose_name='Contact name')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('contact_message', models.TextField(verbose_name='Contact text')),
            ],
        ),
    ]
